import { useLocation, useNavigate } from "react-router-dom";
import "./ResultPage.css";

function ResultPage() {
  const location = useLocation();
  const navigate = useNavigate();

  const predictedPrice = location.state?.predicted_price;

  return (
    <main className="result-page">
      <div className="result-card">
        <div className="result-icon">₹</div>

        <p className="result-label">ESTIMATED PROPERTY PRICE</p>

        {predictedPrice !== undefined ? (
          <h1 className="result-price">
            ₹{Number(predictedPrice).toLocaleString("en-IN", {
              maximumFractionDigits: 0,
            })}
          </h1>
        ) : (
          <h1 className="result-price">No Result</h1>
        )}

        <p className="result-description">
          This is the estimated price generated by the machine learning model
          based on the property details you provided.
        </p>

        <button
          className="result-button"
          onClick={() => navigate("/")}
        >
          Predict Another Property
        </button>
      </div>
    </main>
  );
}

export default ResultPage;